# Site settings
title: Breunig Lab
header-img: img/fetal-bg.jpg
description: "The Breunig Laboratory is investigating the molecular mechanisms that govern the generation of the central nervous system from neural stem cells."
baseurl: ""
url: "http://TheBreunigLab.com"
twitter_username: breuniglab
github_username:  JBreunig

# Google Analytics
## Paul - We need our own google tracking ID google_tracking_id: UA-64316769-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","*.json","README.md","Gemfile","*.lock"]
