# Site settings
title: Breunig Lab
header-img: img/main-page-background.jpg
description: "The Breunig Laboratory at Wake Forest University School of Medicine studies neural development, brain cancer, cell identity, and new technologies for somatic and genome engineering."
baseurl: "/website"
url: "https://jbreunig.github.io"
twitter_username: breuniglab
github_username: JBreunig

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","*.json","README.md","Gemfile","*.lock","CNAME"]
